name: birthday_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+1
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  firebase_auth: ^4.2.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
